DROP TABLE IF EXISTS data1;

CREATE TABLE data1(				
	country		VARCHAR(50),
	year		INT,
	iso_code		VARCHAR(5),
	population		BIGINT,
	gdp							REAL,
	cement_co2								REAL,
	cement_co2_per_capita		REAL,
	co2		REAL,
	co2_growth_abs		REAL,
	co2_growth_prct		REAL,
	co2_including_luc		REAL,
	co2_including_luc_growth_abs		REAL,
	co2_including_luc_growth_prct		REAL,
	co2_including_luc_per_capita		REAL,
	co2_including_luc_per_gdp		REAL,
	co2_including_luc_per_unit_energy		REAL,
	co2_per_capita		REAL,
	co2_per_gdp		REAL,
	co2_per_unit_energy		REAL,
	coal_co2		REAL,
	coal_co2_per_capita		REAL,
	consumption_co2		REAL,
	consumption_co2_per_capita		REAL,
	consumption_co2_per_gdp		REAL,
	cumulative_cement_co2		REAL,
	cumulative_co2		REAL,
	cumulative_co2_including_luc		REAL,
	cumulative_coal_co2		REAL,
	cumulative_flaring_co2		REAL,
	cumulative_gas_co2		REAL,
	cumulative_luc_co2		REAL,
	cumulative_oil_co2		REAL,
	cumulative_other_co2		REAL,
	energy_per_capita		REAL,
	energy_per_gdp		REAL,
	flaring_co2		REAL,
	flaring_co2_per_capita		REAL,
	gas_co2		REAL,
	gas_co2_per_capita		REAL,
	ghg_excluding_lucf_per_capita		REAL,
	ghg_per_capita		REAL,
	land_use_change_co2		REAL,
	land_use_change_co2_per_capita					REAL,
	methane											REAL,
	methane_per_capita								REAL,
	nitrous_oxide									REAL,
	nitrous_oxide_per_capita						REAL,
	oil_co2											REAL,
	oil_co2_per_capita								REAL,
	other_co2_per_capita							REAL,
	other_industry_co2								REAL,
	primary_energy_consumption						REAL,
	share_global_cement_co2							REAL,
	share_global_co2								REAL,
	share_global_co2_including_luc					REAL,
	share_global_coal_co2							REAL,
	share_global_cumulative_cement_co2				REAL,
	share_global_cumulative_co2						REAL,
	share_global_cumulative_co2_including_luc		REAL,
	share_global_cumulative_coal_co2				REAL,
	share_global_cumulative_flaring_co2				REAL,
	share_global_cumulative_gas_co2					REAL,
	share_global_cumulative_luc_co2					REAL,
	share_global_cumulative_oil_co2					REAL,
	share_global_cumulative_other_co2				REAL,
	share_global_flaring_co2						REAL,
	share_global_gas_co2							REAL,
	share_global_luc_co2							REAL,
	share_global_oil_co2							REAL,
	share_global_other_co2							REAL,
	share_of_temperature_change_from_ghg			REAL,
	temperature_change_from_ch4						REAL,
	temperature_change_from_co2						REAL,
	temperature_change_from_ghg						REAL,
	temperature_change_from_n2o						REAL,
	total_ghg										REAL,
	total_ghg_excluding_lucf						REAL,
	trade_co2										REAL,
	trade_co2_share									REAL
);

COPY 
data1 (country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,co2_including_luc_growth_prct,co2_including_luc_per_capita,co2_including_luc_per_gdp,co2_including_luc_per_unit_energy,co2_per_capita,co2_per_gdp,co2_per_unit_energy,coal_co2,coal_co2_per_capita,consumption_co2,consumption_co2_per_capita,consumption_co2_per_gdp,cumulative_cement_co2,cumulative_co2,cumulative_co2_including_luc,cumulative_coal_co2,cumulative_flaring_co2,cumulative_gas_co2,cumulative_luc_co2,cumulative_oil_co2,cumulative_other_co2,energy_per_capita,energy_per_gdp,flaring_co2,flaring_co2_per_capita,gas_co2,gas_co2_per_capita,ghg_excluding_lucf_per_capita,ghg_per_capita,land_use_change_co2,land_use_change_co2_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,oil_co2,oil_co2_per_capita,other_co2_per_capita,other_industry_co2,primary_energy_consumption,share_global_cement_co2,share_global_co2,share_global_co2_including_luc,share_global_coal_co2,share_global_cumulative_cement_co2,share_global_cumulative_co2,share_global_cumulative_co2_including_luc,share_global_cumulative_coal_co2,share_global_cumulative_flaring_co2,share_global_cumulative_gas_co2,share_global_cumulative_luc_co2,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
)
FROM 'D:\owid-co2-data.csv'
DELIMITER','
CSV HEADER;
SELECT * FROM data1;

DELETE FROM data1
WHERE  year<1850 OR ghg_per_capita is NULL;

WITH mins AS (
    SELECT
        country,
        MIN(gdp) AS min_gdp,
        MIN(cement_co2) AS min_cement_co2,
        MIN(cement_co2_per_capita) AS min_cement_co2_per_capita,
        MIN(co2) AS min_co2,
        MIN(co2_growth_abs) AS min_co2_growth_abs,
        MIN(co2_growth_prct) AS min_co2_growth_prct,
        MIN(co2_including_luc) AS min_co2_including_luc,
        MIN(co2_including_luc_growth_abs) AS min_co2_including_luc_growth_abs,
        MIN(co2_including_luc_growth_prct) AS min_co2_including_luc_growth_prct,
        MIN(co2_including_luc_per_capita) AS min_co2_including_luc_per_capita,
        MIN(co2_including_luc_per_gdp) AS min_co2_including_luc_per_gdp,
        MIN(co2_including_luc_per_unit_energy) AS min_co2_including_luc_per_unit_energy,
        MIN(co2_per_capita) AS min_co2_per_capita,
        MIN(co2_per_gdp) AS min_co2_per_gdp,
        MIN(co2_per_unit_energy) AS min_co2_per_unit_energy,
        MIN(coal_co2) AS min_coal_co2,
        MIN(coal_co2_per_capita) AS min_coal_co2_per_capita,
        MIN(consumption_co2) AS min_consumption_co2,
        MIN(consumption_co2_per_capita) AS min_consumption_co2_per_capita,
        MIN(consumption_co2_per_gdp) AS min_consumption_co2_per_gdp,
        MIN(cumulative_cement_co2) AS min_cumulative_cement_co2,
        MIN(cumulative_co2) AS min_cumulative_co2,
        MIN(cumulative_co2_including_luc) AS min_cumulative_co2_including_luc,
        MIN(cumulative_coal_co2) AS min_cumulative_coal_co2,
        MIN(cumulative_flaring_co2) AS min_cumulative_flaring_co2,
        MIN(cumulative_gas_co2) AS min_cumulative_gas_co2,
        MIN(cumulative_luc_co2) AS min_cumulative_luc_co2,
        MIN(cumulative_oil_co2) AS min_cumulative_oil_co2,
        MIN(cumulative_other_co2) AS min_cumulative_other_co2,
        MIN(energy_per_capita) AS min_energy_per_capita,
        MIN(energy_per_gdp) AS min_energy_per_gdp,
        MIN(flaring_co2) AS min_flaring_co2,
        MIN(flaring_co2_per_capita) AS min_flaring_co2_per_capita,
        MIN(gas_co2) AS min_gas_co2,
        MIN(gas_co2_per_capita) AS min_gas_co2_per_capita,
        MIN(ghg_excluding_lucf_per_capita) AS min_ghg_excluding_lucf_per_capita,
        MIN(ghg_per_capita) AS min_ghg_per_capita,
        MIN(land_use_change_co2) AS min_land_use_change_co2,
        MIN(land_use_change_co2_per_capita) AS min_land_use_change_co2_per_capita,
        MIN(methane) AS min_methane,
        MIN(methane_per_capita) AS min_methane_per_capita,
        MIN(nitrous_oxide) AS min_nitrous_oxide,
        MIN(nitrous_oxide_per_capita) AS min_nitrous_oxide_per_capita,
        MIN(oil_co2) AS min_oil_co2,
        MIN(oil_co2_per_capita) AS min_oil_co2_per_capita,
        MIN(other_co2_per_capita) AS min_other_co2_per_capita,
        MIN(other_industry_co2) AS min_other_industry_co2,
        MIN(primary_energy_consumption) AS min_primary_energy_consumption,
        MIN(share_global_cement_co2) AS min_share_global_cement_co2,
        MIN(share_global_co2) AS min_share_global_co2,
        MIN(share_global_co2_including_luc) AS min_share_global_co2_including_luc,
        MIN(share_global_coal_co2) AS min_share_global_coal_co2,
        MIN(share_global_cumulative_cement_co2) AS min_share_global_cumulative_cement_co2,
        MIN(share_global_cumulative_co2) AS min_share_global_cumulative_co2,
        MIN(share_global_cumulative_co2_including_luc) AS min_share_global_cumulative_co2_including_luc,
        MIN(share_global_cumulative_coal_co2) AS min_share_global_cumulative_coal_co2,
        MIN(share_global_cumulative_flaring_co2) AS min_share_global_cumulative_flaring_co2,
        MIN(share_global_cumulative_gas_co2) AS min_share_global_cumulative_gas_co2,
        MIN(share_global_cumulative_luc_co2) AS min_share_global_cumulative_luc_co2,
        MIN(share_global_cumulative_oil_co2) AS min_share_global_cumulative_oil_co2,
        MIN(share_global_cumulative_other_co2) AS min_share_global_cumulative_other_co2,
        MIN(share_global_flaring_co2) AS min_share_global_flaring_co2,
        MIN(share_global_gas_co2) AS min_share_global_gas_co2,
        MIN(share_global_luc_co2) AS min_share_global_luc_co2,
        MIN(share_global_oil_co2) AS min_share_global_oil_co2,
        MIN(share_global_other_co2) AS min_share_global_other_co2,
        MIN(share_of_temperature_change_from_ghg) AS min_share_of_temperature_change_from_ghg,
        MIN(temperature_change_from_ch4) AS min_temperature_change_from_ch4,
        MIN(temperature_change_from_co2) AS min_temperature_change_from_co2,
        MIN(temperature_change_from_ghg) AS min_temperature_change_from_ghg,
        MIN(temperature_change_from_n2o) AS min_temperature_change_from_n2o,
        MIN(total_ghg) AS min_total_ghg,
        MIN(total_ghg_excluding_lucf) AS min_total_ghg_excluding_lucf,
        MIN(trade_co2) AS min_trade_co2,
        MIN(trade_co2_share) AS min_trade_co2_share
    FROM data1
    GROUP BY country
)

UPDATE data1 AS c
SET
    gdp = COALESCE(c.gdp, a.min_gdp),
    cement_co2 = COALESCE(c.cement_co2, a.min_cement_co2),
    cement_co2_per_capita = COALESCE(c.cement_co2_per_capita, a.min_cement_co2_per_capita),
    co2 = COALESCE(c.co2, a.min_co2),
    co2_growth_abs = COALESCE(c.co2_growth_abs, a.min_co2_growth_abs),
    co2_growth_prct = COALESCE(c.co2_growth_prct, a.min_co2_growth_prct),
    co2_including_luc = COALESCE(c.co2_including_luc, a.min_co2_including_luc),
    co2_including_luc_growth_abs = COALESCE(c.co2_including_luc_growth_abs, a.min_co2_including_luc_growth_abs),
    co2_including_luc_growth_prct = COALESCE(c.co2_including_luc_growth_prct, a.min_co2_including_luc_growth_prct),
    co2_including_luc_per_capita = COALESCE(c.co2_including_luc_per_capita, a.min_co2_including_luc_per_capita),
    co2_including_luc_per_gdp = COALESCE(c.co2_including_luc_per_gdp, a.min_co2_including_luc_per_gdp),
    co2_including_luc_per_unit_energy = COALESCE(c.co2_including_luc_per_unit_energy, a.min_co2_including_luc_per_unit_energy),
    co2_per_capita = COALESCE(c.co2_per_capita, a.min_co2_per_capita),
    co2_per_gdp = COALESCE(c.co2_per_gdp, a.min_co2_per_gdp),
    co2_per_unit_energy = COALESCE(c.co2_per_unit_energy, a.min_co2_per_unit_energy),
    coal_co2 = COALESCE(c.coal_co2, a.min_coal_co2),
    coal_co2_per_capita = COALESCE(c.coal_co2_per_capita, a.min_coal_co2_per_capita),
    consumption_co2 = COALESCE(c.consumption_co2, a.min_consumption_co2),
    consumption_co2_per_capita = COALESCE(c.consumption_co2_per_capita, a.min_consumption_co2_per_capita),
    consumption_co2_per_gdp = COALESCE(c.consumption_co2_per_gdp, a.min_consumption_co2_per_gdp),
    cumulative_cement_co2 = COALESCE(c.cumulative_cement_co2, a.min_cumulative_cement_co2),
    cumulative_co2 = COALESCE(c.cumulative_co2, a.min_cumulative_co2),
    cumulative_co2_including_luc = COALESCE(c.cumulative_co2_including_luc, a.min_cumulative_co2_including_luc),
    cumulative_coal_co2 = COALESCE(c.cumulative_coal_co2, a.min_cumulative_coal_co2),
    cumulative_flaring_co2 = COALESCE(c.cumulative_flaring_co2, a.min_cumulative_flaring_co2),
    cumulative_gas_co2 = COALESCE(c.cumulative_gas_co2, a.min_cumulative_gas_co2),
    cumulative_luc_co2 = COALESCE(c.cumulative_luc_co2, a.min_cumulative_luc_co2),
    cumulative_oil_co2 = COALESCE(c.cumulative_oil_co2, a.min_cumulative_oil_co2),
    cumulative_other_co2 = COALESCE(c.cumulative_other_co2, a.min_cumulative_other_co2),
    energy_per_capita = COALESCE(c.energy_per_capita, a.min_energy_per_capita),
    energy_per_gdp = COALESCE(c.energy_per_gdp, a.min_energy_per_gdp),
    flaring_co2 = COALESCE(c.flaring_co2, a.min_flaring_co2),
    flaring_co2_per_capita = COALESCE(c.flaring_co2_per_capita, a.min_flaring_co2_per_capita),
    gas_co2 = COALESCE(c.gas_co2, a.min_gas_co2),
    gas_co2_per_capita = COALESCE(c.gas_co2_per_capita, a.min_gas_co2_per_capita),
    ghg_excluding_lucf_per_capita = COALESCE(c.ghg_excluding_lucf_per_capita, a.min_ghg_excluding_lucf_per_capita),
    ghg_per_capita = COALESCE(c.ghg_per_capita, a.min_ghg_per_capita),
    land_use_change_co2 = COALESCE(c.land_use_change_co2, a.min_land_use_change_co2),
    land_use_change_co2_per_capita = COALESCE(c.land_use_change_co2_per_capita, a.min_land_use_change_co2_per_capita),
    methane = COALESCE(c.methane, a.min_methane),
    methane_per_capita = COALESCE(c.methane_per_capita, a.min_methane_per_capita),
    nitrous_oxide = COALESCE(c.nitrous_oxide, a.min_nitrous_oxide),
    nitrous_oxide_per_capita = COALESCE(c.nitrous_oxide_per_capita, a.min_nitrous_oxide_per_capita),
    oil_co2 = COALESCE(c.oil_co2, a.min_oil_co2),
    oil_co2_per_capita = COALESCE(c.oil_co2_per_capita, a.min_oil_co2_per_capita),
    other_co2_per_capita = COALESCE(c.other_co2_per_capita, a.min_other_co2_per_capita),
    other_industry_co2 = COALESCE(c.other_industry_co2, a.min_other_industry_co2),
    primary_energy_consumption = COALESCE(c.primary_energy_consumption, a.min_primary_energy_consumption),
    share_global_cement_co2 = COALESCE(c.share_global_cement_co2, a.min_share_global_cement_co2),
    share_global_co2 = COALESCE(c.share_global_co2, a.min_share_global_co2),
    share_global_co2_including_luc = COALESCE(c.share_global_co2_including_luc, a.min_share_global_co2_including_luc),
    share_global_coal_co2 = COALESCE(c.share_global_coal_co2, a.min_share_global_coal_co2),
    share_global_cumulative_cement_co2 = COALESCE(c.share_global_cumulative_cement_co2, a.min_share_global_cumulative_cement_co2),
    share_global_cumulative_co2 = COALESCE(c.share_global_cumulative_co2, a.min_share_global_cumulative_co2),
    share_global_cumulative_co2_including_luc = COALESCE(c.share_global_cumulative_co2_including_luc, a.min_share_global_cumulative_co2_including_luc),
    share_global_cumulative_coal_co2 = COALESCE(c.share_global_cumulative_coal_co2, a.min_share_global_cumulative_coal_co2),
    share_global_cumulative_flaring_co2 = COALESCE(c.share_global_cumulative_flaring_co2, a.min_share_global_cumulative_flaring_co2),
    share_global_cumulative_gas_co2 = COALESCE(c.share_global_cumulative_gas_co2, a.min_share_global_cumulative_gas_co2),
    share_global_cumulative_luc_co2 = COALESCE(c.share_global_cumulative_luc_co2, a.min_share_global_cumulative_luc_co2),
    share_global_cumulative_oil_co2 = COALESCE(c.share_global_cumulative_oil_co2, a.min_share_global_cumulative_oil_co2),
    share_global_cumulative_other_co2 = COALESCE(c.share_global_cumulative_other_co2, a.min_share_global_cumulative_other_co2),
    share_global_flaring_co2 = COALESCE(c.share_global_flaring_co2, a.min_share_global_flaring_co2),
    share_global_gas_co2 = COALESCE(c.share_global_gas_co2, a.min_share_global_gas_co2),
    share_global_luc_co2 = COALESCE(c.share_global_luc_co2, a.min_share_global_luc_co2),
    share_global_oil_co2 = COALESCE(c.share_global_oil_co2, a.min_share_global_oil_co2),
    share_global_other_co2 = COALESCE(c.share_global_other_co2, a.min_share_global_other_co2),
    share_of_temperature_change_from_ghg = COALESCE(c.share_of_temperature_change_from_ghg, a.min_share_of_temperature_change_from_ghg),
    temperature_change_from_ch4 = COALESCE(c.temperature_change_from_ch4, a.min_temperature_change_from_ch4),
    temperature_change_from_co2 = COALESCE(c.temperature_change_from_co2, a.min_temperature_change_from_co2),
    temperature_change_from_ghg = COALESCE(c.temperature_change_from_ghg, a.min_temperature_change_from_ghg),
    temperature_change_from_n2o = COALESCE(c.temperature_change_from_n2o, a.min_temperature_change_from_n2o),
    total_ghg = COALESCE(c.total_ghg, a.min_total_ghg),
    total_ghg_excluding_lucf = COALESCE(c.total_ghg_excluding_lucf, a.min_total_ghg_excluding_lucf),
    trade_co2 = COALESCE(c.trade_co2, a.min_trade_co2),
    trade_co2_share = COALESCE(c.trade_co2_share, a.min_trade_co2_share)
FROM mins AS a
WHERE c.country = a.country;

ALTER TABLE data1
DROP COLUMN consumption_co2,
DROP COLUMN consumption_co2_per_capita,
DROP COLUMN consumption_co2_per_gdp,
DROP COLUMN	cumulative_other_co2,
DROP COLUMN	other_co2_per_capita,
DROP COLUMN	other_industry_co2,
DROP COLUMN	share_global_cumulative_other_co2,
DROP COLUMN	share_global_other_co2,
DROP COLUMN trade_co2,
DROP COLUMN trade_co2_share;

SELECT * FROM data1;