DROP TABLE IF EXISTS data1;

CREATE TABLE data1(				
	country		VARCHAR(50),
	year		INT,
	iso_code		VARCHAR(5),
	population		BIGINT,
	gdp							REAL,
	cement_co2								REAL,
	cement_co2_per_capita		REAL,
	co2		REAL,
	co2_growth_abs		REAL,
	co2_growth_prct		REAL,
	co2_including_luc		REAL,
	co2_including_luc_growth_abs		REAL,
	co2_including_luc_growth_prct		REAL,
	co2_including_luc_per_capita		REAL,
	co2_including_luc_per_gdp		REAL,
	co2_including_luc_per_unit_energy		REAL,
	co2_per_capita		REAL,
	co2_per_gdp		REAL,
	co2_per_unit_energy		REAL,
	coal_co2		REAL,
	coal_co2_per_capita		REAL,
	consumption_co2		REAL,
	consumption_co2_per_capita		REAL,
	consumption_co2_per_gdp		REAL,
	cumulative_cement_co2		REAL,
	cumulative_co2		REAL,
	cumulative_co2_including_luc		REAL,
	cumulative_coal_co2		REAL,
	cumulative_flaring_co2		REAL,
	cumulative_gas_co2		REAL,
	cumulative_luc_co2		REAL,
	cumulative_oil_co2		REAL,
	cumulative_other_co2		REAL,
	energy_per_capita		REAL,
	energy_per_gdp		REAL,
	flaring_co2		REAL,
	flaring_co2_per_capita		REAL,
	gas_co2		REAL,
	gas_co2_per_capita		REAL,
	ghg_excluding_lucf_per_capita		REAL,
	ghg_per_capita		REAL,
	land_use_change_co2		REAL,
	land_use_change_co2_per_capita					REAL,
	methane											REAL,
	methane_per_capita								REAL,
	nitrous_oxide									REAL,
	nitrous_oxide_per_capita						REAL,
	oil_co2											REAL,
	oil_co2_per_capita								REAL,
	other_co2_per_capita							REAL,
	other_industry_co2								REAL,
	primary_energy_consumption						REAL,
	share_global_cement_co2							REAL,
	share_global_co2								REAL,
	share_global_co2_including_luc					REAL,
	share_global_coal_co2							REAL,
	share_global_cumulative_cement_co2				REAL,
	share_global_cumulative_co2						REAL,
	share_global_cumulative_co2_including_luc		REAL,
	share_global_cumulative_coal_co2				REAL,
	share_global_cumulative_flaring_co2				REAL,
	share_global_cumulative_gas_co2					REAL,
	share_global_cumulative_luc_co2					REAL,
	share_global_cumulative_oil_co2					REAL,
	share_global_cumulative_other_co2				REAL,
	share_global_flaring_co2						REAL,
	share_global_gas_co2							REAL,
	share_global_luc_co2							REAL,
	share_global_oil_co2							REAL,
	share_global_other_co2							REAL,
	share_of_temperature_change_from_ghg			REAL,
	temperature_change_from_ch4						REAL,
	temperature_change_from_co2						REAL,
	temperature_change_from_ghg						REAL,
	temperature_change_from_n2o						REAL,
	total_ghg										REAL,
	total_ghg_excluding_lucf						REAL,
	trade_co2										REAL,
	trade_co2_share									REAL
);

COPY 
data1 (country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,co2_including_luc_growth_prct,co2_including_luc_per_capita,co2_including_luc_per_gdp,co2_including_luc_per_unit_energy,co2_per_capita,co2_per_gdp,co2_per_unit_energy,coal_co2,coal_co2_per_capita,consumption_co2,consumption_co2_per_capita,consumption_co2_per_gdp,cumulative_cement_co2,cumulative_co2,cumulative_co2_including_luc,cumulative_coal_co2,cumulative_flaring_co2,cumulative_gas_co2,cumulative_luc_co2,cumulative_oil_co2,cumulative_other_co2,energy_per_capita,energy_per_gdp,flaring_co2,flaring_co2_per_capita,gas_co2,gas_co2_per_capita,ghg_excluding_lucf_per_capita,ghg_per_capita,land_use_change_co2,land_use_change_co2_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,oil_co2,oil_co2_per_capita,other_co2_per_capita,other_industry_co2,primary_energy_consumption,share_global_cement_co2,share_global_co2,share_global_co2_including_luc,share_global_coal_co2,share_global_cumulative_cement_co2,share_global_cumulative_co2,share_global_cumulative_co2_including_luc,share_global_cumulative_coal_co2,share_global_cumulative_flaring_co2,share_global_cumulative_gas_co2,share_global_cumulative_luc_co2,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
)
FROM 'D:\owid-co2-data.csv'
DELIMITER','
CSV HEADER;
SELECT * FROM data1;

DELETE FROM data1
WHERE  year<1850 OR ghg_per_capita is NULL OR iso_code is NULL;

WITH avgs AS (
    SELECT
        country,
        AVG(gdp) AS avg_gdp,
        AVG(cement_co2) AS avg_cement_co2,
        AVG(cement_co2_per_capita) AS avg_cement_co2_per_capita,
        AVG(co2) AS avg_co2,
        AVG(co2_growth_abs) AS avg_co2_growth_abs,
        AVG(co2_growth_prct) AS avg_co2_growth_prct,
        AVG(co2_including_luc) AS avg_co2_including_luc,
        AVG(co2_including_luc_growth_abs) AS avg_co2_including_luc_growth_abs,
        AVG(co2_including_luc_growth_prct) AS avg_co2_including_luc_growth_prct,
        AVG(co2_including_luc_per_capita) AS avg_co2_including_luc_per_capita,
        AVG(co2_including_luc_per_gdp) AS avg_co2_including_luc_per_gdp,
        AVG(co2_including_luc_per_unit_energy) AS avg_co2_including_luc_per_unit_energy,
        AVG(co2_per_capita) AS avg_co2_per_capita,
        AVG(co2_per_gdp) AS avg_co2_per_gdp,
        AVG(co2_per_unit_energy) AS avg_co2_per_unit_energy,
        AVG(coal_co2) AS avg_coal_co2,
        AVG(coal_co2_per_capita) AS avg_coal_co2_per_capita,
        AVG(consumption_co2) AS avg_consumption_co2,
        AVG(consumption_co2_per_capita) AS avg_consumption_co2_per_capita,
        AVG(consumption_co2_per_gdp) AS avg_consumption_co2_per_gdp,
        AVG(cumulative_cement_co2) AS avg_cumulative_cement_co2,
        AVG(cumulative_co2) AS avg_cumulative_co2,
        AVG(cumulative_co2_including_luc) AS avg_cumulative_co2_including_luc,
        AVG(cumulative_coal_co2) AS avg_cumulative_coal_co2,
        AVG(cumulative_flaring_co2) AS avg_cumulative_flaring_co2,
        AVG(cumulative_gas_co2) AS avg_cumulative_gas_co2,
        AVG(cumulative_luc_co2) AS avg_cumulative_luc_co2,
        AVG(cumulative_oil_co2) AS avg_cumulative_oil_co2,
        AVG(cumulative_other_co2) AS avg_cumulative_other_co2,
        AVG(energy_per_capita) AS avg_energy_per_capita,
        AVG(energy_per_gdp) AS avg_energy_per_gdp,
        AVG(flaring_co2) AS avg_flaring_co2,
        AVG(flaring_co2_per_capita) AS avg_flaring_co2_per_capita,
        AVG(gas_co2) AS avg_gas_co2,
        AVG(gas_co2_per_capita) AS avg_gas_co2_per_capita,
        AVG(ghg_excluding_lucf_per_capita) AS avg_ghg_excluding_lucf_per_capita,
        AVG(ghg_per_capita) AS avg_ghg_per_capita,
        AVG(land_use_change_co2) AS avg_land_use_change_co2,
        AVG(land_use_change_co2_per_capita) AS avg_land_use_change_co2_per_capita,
        AVG(methane) AS avg_methane,
        AVG(methane_per_capita) AS avg_methane_per_capita,
        AVG(nitrous_oxide) AS avg_nitrous_oxide,
        AVG(nitrous_oxide_per_capita) AS avg_nitrous_oxide_per_capita,
        AVG(oil_co2) AS avg_oil_co2,
        AVG(oil_co2_per_capita) AS avg_oil_co2_per_capita,
        AVG(other_co2_per_capita) AS avg_other_co2_per_capita,
        AVG(other_industry_co2) AS avg_other_industry_co2,
        AVG(primary_energy_consumption) AS avg_primary_energy_consumption,
        AVG(share_global_cement_co2) AS avg_share_global_cement_co2,
        AVG(share_global_co2) AS avg_share_global_co2,
        AVG(share_global_co2_including_luc) AS avg_share_global_co2_including_luc,
        AVG(share_global_coal_co2) AS avg_share_global_coal_co2,
        AVG(share_global_cumulative_cement_co2) AS avg_share_global_cumulative_cement_co2,
        AVG(share_global_cumulative_co2) AS avg_share_global_cumulative_co2,
        AVG(share_global_cumulative_co2_including_luc) AS avg_share_global_cumulative_co2_including_luc,
        AVG(share_global_cumulative_coal_co2) AS avg_share_global_cumulative_coal_co2,
        AVG(share_global_cumulative_flaring_co2) AS avg_share_global_cumulative_flaring_co2,
        AVG(share_global_cumulative_gas_co2) AS avg_share_global_cumulative_gas_co2,
        AVG(share_global_cumulative_luc_co2) AS avg_share_global_cumulative_luc_co2,
        AVG(share_global_cumulative_oil_co2) AS avg_share_global_cumulative_oil_co2,
        AVG(share_global_cumulative_other_co2) AS avg_share_global_cumulative_other_co2,
        AVG(share_global_flaring_co2) AS avg_share_global_flaring_co2,
        AVG(share_global_gas_co2) AS avg_share_global_gas_co2,
        AVG(share_global_luc_co2) AS avg_share_global_luc_co2,
        AVG(share_global_oil_co2) AS avg_share_global_oil_co2,
        AVG(share_global_other_co2) AS avg_share_global_other_co2,
        AVG(share_of_temperature_change_from_ghg) AS avg_share_of_temperature_change_from_ghg,
        AVG(temperature_change_from_ch4) AS avg_temperature_change_from_ch4,
        AVG(temperature_change_from_co2) AS avg_temperature_change_from_co2,
        AVG(temperature_change_from_ghg) AS avg_temperature_change_from_ghg,
        AVG(temperature_change_from_n2o) AS avg_temperature_change_from_n2o,
        AVG(total_ghg) AS avg_total_ghg,
        AVG(total_ghg_excluding_lucf) AS avg_total_ghg_excluding_lucf,
        AVG(trade_co2) AS avg_trade_co2,
        AVG(trade_co2_share) AS avg_trade_co2_share
    FROM data1
    GROUP BY country
)

UPDATE data1 AS c
SET
    gdp = COALESCE(c.gdp, a.avg_gdp),
    cement_co2 = COALESCE(c.cement_co2, a.avg_cement_co2),
    cement_co2_per_capita = COALESCE(c.cement_co2_per_capita, a.avg_cement_co2_per_capita),
    co2 = COALESCE(c.co2, a.avg_co2),
    co2_growth_abs = COALESCE(c.co2_growth_abs, a.avg_co2_growth_abs),
    co2_growth_prct = COALESCE(c.co2_growth_prct, a.avg_co2_growth_prct),
    co2_including_luc = COALESCE(c.co2_including_luc, a.avg_co2_including_luc),
    co2_including_luc_growth_abs = COALESCE(c.co2_including_luc_growth_abs, a.avg_co2_including_luc_growth_abs),
    co2_including_luc_growth_prct = COALESCE(c.co2_including_luc_growth_prct, a.avg_co2_including_luc_growth_prct),
    co2_including_luc_per_capita = COALESCE(c.co2_including_luc_per_capita, a.avg_co2_including_luc_per_capita),
    co2_including_luc_per_gdp = COALESCE(c.co2_including_luc_per_gdp, a.avg_co2_including_luc_per_gdp),
    co2_including_luc_per_unit_energy = COALESCE(c.co2_including_luc_per_unit_energy, a.avg_co2_including_luc_per_unit_energy),
    co2_per_capita = COALESCE(c.co2_per_capita, a.avg_co2_per_capita),
    co2_per_gdp = COALESCE(c.co2_per_gdp, a.avg_co2_per_gdp),
    co2_per_unit_energy = COALESCE(c.co2_per_unit_energy, a.avg_co2_per_unit_energy),
    coal_co2 = COALESCE(c.coal_co2, a.avg_coal_co2),
    coal_co2_per_capita = COALESCE(c.coal_co2_per_capita, a.avg_coal_co2_per_capita),
    consumption_co2 = COALESCE(c.consumption_co2, a.avg_consumption_co2),
    consumption_co2_per_capita = COALESCE(c.consumption_co2_per_capita, a.avg_consumption_co2_per_capita),
    consumption_co2_per_gdp = COALESCE(c.consumption_co2_per_gdp, a.avg_consumption_co2_per_gdp),
    cumulative_cement_co2 = COALESCE(c.cumulative_cement_co2, a.avg_cumulative_cement_co2),
    cumulative_co2 = COALESCE(c.cumulative_co2, a.avg_cumulative_co2),
    cumulative_co2_including_luc = COALESCE(c.cumulative_co2_including_luc, a.avg_cumulative_co2_including_luc),
    cumulative_coal_co2 = COALESCE(c.cumulative_coal_co2, a.avg_cumulative_coal_co2),
    cumulative_flaring_co2 = COALESCE(c.cumulative_flaring_co2, a.avg_cumulative_flaring_co2),
    cumulative_gas_co2 = COALESCE(c.cumulative_gas_co2, a.avg_cumulative_gas_co2),
    cumulative_luc_co2 = COALESCE(c.cumulative_luc_co2, a.avg_cumulative_luc_co2),
    cumulative_oil_co2 = COALESCE(c.cumulative_oil_co2, a.avg_cumulative_oil_co2),
    cumulative_other_co2 = COALESCE(c.cumulative_other_co2, a.avg_cumulative_other_co2),
    energy_per_capita = COALESCE(c.energy_per_capita, a.avg_energy_per_capita),
    energy_per_gdp = COALESCE(c.energy_per_gdp, a.avg_energy_per_gdp),
    flaring_co2 = COALESCE(c.flaring_co2, a.avg_flaring_co2),
    flaring_co2_per_capita = COALESCE(c.flaring_co2_per_capita, a.avg_flaring_co2_per_capita),
    gas_co2 = COALESCE(c.gas_co2, a.avg_gas_co2),
    gas_co2_per_capita = COALESCE(c.gas_co2_per_capita, a.avg_gas_co2_per_capita),
    ghg_excluding_lucf_per_capita = COALESCE(c.ghg_excluding_lucf_per_capita, a.avg_ghg_excluding_lucf_per_capita),
    ghg_per_capita = COALESCE(c.ghg_per_capita, a.avg_ghg_per_capita),
    land_use_change_co2 = COALESCE(c.land_use_change_co2, a.avg_land_use_change_co2),
    land_use_change_co2_per_capita = COALESCE(c.land_use_change_co2_per_capita, a.avg_land_use_change_co2_per_capita),
    methane = COALESCE(c.methane, a.avg_methane),
    methane_per_capita = COALESCE(c.methane_per_capita, a.avg_methane_per_capita),
    nitrous_oxide = COALESCE(c.nitrous_oxide, a.avg_nitrous_oxide),
    nitrous_oxide_per_capita = COALESCE(c.nitrous_oxide_per_capita, a.avg_nitrous_oxide_per_capita),
    oil_co2 = COALESCE(c.oil_co2, a.avg_oil_co2),
    oil_co2_per_capita = COALESCE(c.oil_co2_per_capita, a.avg_oil_co2_per_capita),
    other_co2_per_capita = COALESCE(c.other_co2_per_capita, a.avg_other_co2_per_capita),
    other_industry_co2 = COALESCE(c.other_industry_co2, a.avg_other_industry_co2),
    primary_energy_consumption = COALESCE(c.primary_energy_consumption, a.avg_primary_energy_consumption),
    share_global_cement_co2 = COALESCE(c.share_global_cement_co2, a.avg_share_global_cement_co2),
    share_global_co2 = COALESCE(c.share_global_co2, a.avg_share_global_co2),
    share_global_co2_including_luc = COALESCE(c.share_global_co2_including_luc, a.avg_share_global_co2_including_luc),
    share_global_coal_co2 = COALESCE(c.share_global_coal_co2, a.avg_share_global_coal_co2),
    share_global_cumulative_cement_co2 = COALESCE(c.share_global_cumulative_cement_co2, a.avg_share_global_cumulative_cement_co2),
    share_global_cumulative_co2 = COALESCE(c.share_global_cumulative_co2, a.avg_share_global_cumulative_co2),
    share_global_cumulative_co2_including_luc = COALESCE(c.share_global_cumulative_co2_including_luc, a.avg_share_global_cumulative_co2_including_luc),
    share_global_cumulative_coal_co2 = COALESCE(c.share_global_cumulative_coal_co2, a.avg_share_global_cumulative_coal_co2),
    share_global_cumulative_flaring_co2 = COALESCE(c.share_global_cumulative_flaring_co2, a.avg_share_global_cumulative_flaring_co2),
    share_global_cumulative_gas_co2 = COALESCE(c.share_global_cumulative_gas_co2, a.avg_share_global_cumulative_gas_co2),
    share_global_cumulative_luc_co2 = COALESCE(c.share_global_cumulative_luc_co2, a.avg_share_global_cumulative_luc_co2),
    share_global_cumulative_oil_co2 = COALESCE(c.share_global_cumulative_oil_co2, a.avg_share_global_cumulative_oil_co2),
    share_global_cumulative_other_co2 = COALESCE(c.share_global_cumulative_other_co2, a.avg_share_global_cumulative_other_co2),
    share_global_flaring_co2 = COALESCE(c.share_global_flaring_co2, a.avg_share_global_flaring_co2),
    share_global_gas_co2 = COALESCE(c.share_global_gas_co2, a.avg_share_global_gas_co2),
    share_global_luc_co2 = COALESCE(c.share_global_luc_co2, a.avg_share_global_luc_co2),
    share_global_oil_co2 = COALESCE(c.share_global_oil_co2, a.avg_share_global_oil_co2),
    share_global_other_co2 = COALESCE(c.share_global_other_co2, a.avg_share_global_other_co2),
    share_of_temperature_change_from_ghg = COALESCE(c.share_of_temperature_change_from_ghg, a.avg_share_of_temperature_change_from_ghg),
    temperature_change_from_ch4 = COALESCE(c.temperature_change_from_ch4, a.avg_temperature_change_from_ch4),
    temperature_change_from_co2 = COALESCE(c.temperature_change_from_co2, a.avg_temperature_change_from_co2),
    temperature_change_from_ghg = COALESCE(c.temperature_change_from_ghg, a.avg_temperature_change_from_ghg),
    temperature_change_from_n2o = COALESCE(c.temperature_change_from_n2o, a.avg_temperature_change_from_n2o),
    total_ghg = COALESCE(c.total_ghg, a.avg_total_ghg),
    total_ghg_excluding_lucf = COALESCE(c.total_ghg_excluding_lucf, a.avg_total_ghg_excluding_lucf),
    trade_co2 = COALESCE(c.trade_co2, a.avg_trade_co2),
    trade_co2_share = COALESCE(c.trade_co2_share, a.avg_trade_co2_share)
FROM avgs AS a
WHERE c.country = a.country;

ALTER TABLE data1
DROP COLUMN consumption_co2,
DROP COLUMN consumption_co2_per_capita,
DROP COLUMN consumption_co2_per_gdp,
DROP COLUMN	cumulative_other_co2,
DROP COLUMN	other_co2_per_capita,
DROP COLUMN	other_industry_co2,
DROP COLUMN	share_global_cumulative_other_co2,
DROP COLUMN	share_global_other_co2,
DROP COLUMN trade_co2,
DROP COLUMN trade_co2_share;

UPDATE data1
SET gdp=0
WHERE gdp is NULL;

SELECT * FROM data1;

